// GroupAuth — mock fixtures for development and Storybook stories
// Companies, users, roles, and activity data match the wireframes exactly.

import type { Company, User, Role, Activity, LoginEvent } from '@/types'

export const COMPANIES: Company[] = [
  {
    id: 'cympire',
    name: 'Cympire',
    domain: 'cympire.com',
    userCount: 64,
    activeCount: 38,
    mfaEnabled: true,
    aiInsight: 'MFA adoption increased 12% this month — highest across all companies',
  },
  {
    id: 'cywareness',
    name: 'Cywareness',
    domain: 'cywareness.io',
    userCount: 52,
    activeCount: 28,
    mfaEnabled: true,
    aiInsight: "3 users haven't logged in for 30+ days — consider account review",
  },
  {
    id: 'codeus',
    name: 'Codeus Education',
    domain: 'codeus.co.il',
    userCount: 71,
    activeCount: 41,
    mfaEnabled: false,
    aiInsight: 'Login success rate improved to 98.2%, up from 94.1% last week',
  },
  {
    id: 'bina',
    name: 'Bina',
    domain: 'bina.org.il',
    userCount: 48,
    activeCount: 22,
    mfaEnabled: true,
    aiInsight: '5 pending invites older than 7 days — may need resending',
  },
  {
    id: 'soterio',
    name: 'Soterio',
    domain: 'soterio.com',
    userCount: 52,
    activeCount: 14,
    mfaEnabled: false,
    aiInsight: 'Unusual login pattern detected from new IP range in last 48h',
  },
]

export const USERS: User[] = [
  {
    id: 'u1',
    name: 'Sarah Chen',
    email: 'sarah.chen@cympire.com',
    company: 'cympire',
    role: 'Company Admin',
    status: 'active',
    lastLogin: '2 min ago',
    mfaEnabled: true,
    avatarInitials: 'SC',
  },
  {
    id: 'u2',
    name: 'Michael Torres',
    email: 'michael.torres@cywareness.io',
    company: 'cywareness',
    role: 'Manager',
    status: 'active',
    lastLogin: '5 min ago',
    mfaEnabled: true,
    avatarInitials: 'MT',
  },
  {
    id: 'u3',
    name: 'James Lee',
    email: 'james.lee@codeus.co.il',
    company: 'codeus',
    role: 'Viewer',
    status: 'pending',
    lastLogin: 'Never',
    mfaEnabled: false,
    avatarInitials: 'JL',
  },
  {
    id: 'u4',
    name: 'Sophia Martinez',
    email: 'sophia.martinez@bina.org.il',
    company: 'bina',
    role: 'Manager',
    status: 'disabled',
    lastLogin: '30 days ago',
    mfaEnabled: false,
    avatarInitials: 'SM',
  },
  {
    id: 'u5',
    name: 'David Cohen',
    email: 'david.cohen@soterio.com',
    company: 'soterio',
    role: 'Viewer',
    status: 'active',
    lastLogin: '1 hour ago',
    mfaEnabled: true,
    avatarInitials: 'DC',
  },
  {
    id: 'u6',
    name: 'Anat Levi',
    email: 'anat.levi@cympire.com',
    company: 'cympire',
    role: 'Manager',
    status: 'active',
    lastLogin: '3 hours ago',
    mfaEnabled: true,
    avatarInitials: 'AL',
  },
  {
    id: 'u7',
    name: 'Ronen Shapira',
    email: 'ronen.shapira@cywareness.io',
    company: 'cywareness',
    role: 'Company Admin',
    status: 'active',
    lastLogin: '1 day ago',
    mfaEnabled: false,
    avatarInitials: 'RS',
  },
  {
    id: 'u8',
    name: 'Emily Johnson',
    email: 'emily.johnson@bina.org.il',
    company: 'bina',
    role: 'Viewer',
    status: 'pending',
    lastLogin: 'Never',
    mfaEnabled: false,
    avatarInitials: 'EJ',
  },
  {
    id: 'u9',
    name: 'Omar Hassan',
    email: 'omar.hassan@soterio.com',
    company: 'soterio',
    role: 'Manager',
    status: 'active',
    lastLogin: '2 days ago',
    mfaEnabled: true,
    avatarInitials: 'OH',
  },
  {
    id: 'u10',
    name: 'Noa Ben-David',
    email: 'noa.bendavid@codeus.co.il',
    company: 'codeus',
    role: 'Company Admin',
    status: 'active',
    lastLogin: '4 hours ago',
    mfaEnabled: true,
    avatarInitials: 'NB',
  },
]

export const ROLES: Role[] = [
  {
    id: 'r1',
    name: 'Super Admin',
    description: 'Full system access across all companies',
    userCount: 2,
    companyScopes: ['cympire', 'cywareness', 'codeus', 'bina', 'soterio'],
    permissions: [],
  },
  {
    id: 'r2',
    name: 'Company Admin',
    description: 'Full access within assigned company',
    userCount: 5,
    companyScopes: ['cympire', 'cywareness', 'codeus'],
    permissions: [],
  },
  {
    id: 'r3',
    name: 'Manager',
    description: 'Manage users and view reports',
    userCount: 18,
    companyScopes: ['cympire', 'cywareness'],
    permissions: [],
  },
  {
    id: 'r4',
    name: 'Viewer',
    description: 'Read-only access to assigned resources',
    userCount: 42,
    companyScopes: ['bina'],
    permissions: [],
  },
  {
    id: 'r5',
    name: 'Custom',
    description: 'Customized permission set',
    userCount: 3,
    companyScopes: ['soterio'],
    permissions: [],
  },
]

export const RECENT_ACTIVITY: Activity[] = [
  { id: 'a1', user: 'Sarah Chen', company: 'cympire', action: 'Logged in', time: '2 min ago' },
  { id: 'a2', user: 'Michael Torres', company: 'cywareness', action: 'Password changed', time: '5 min ago' },
  { id: 'a3', user: 'James Lee', company: 'codeus', action: 'Invited', time: '10 min ago' },
  { id: 'a4', user: 'Sophia Martinez', company: 'bina', action: 'Account disabled', time: '1 hour ago' },
  { id: 'a5', user: 'David Cohen', company: 'soterio', action: 'MFA enabled', time: '2 hours ago' },
  { id: 'a6', user: 'Anat Levi', company: 'cympire', action: 'Role changed', time: '3 hours ago' },
]

export const LOGIN_HISTORY: LoginEvent[] = [
  {
    id: 'l1',
    userId: 'u1',
    ip: '185.34.22.11',
    location: 'Tel Aviv, IL',
    device: 'Chrome / macOS',
    status: 'success',
    timestamp: '2 min ago',
  },
  {
    id: 'l2',
    userId: 'u1',
    ip: '185.34.22.11',
    location: 'Tel Aviv, IL',
    device: 'Chrome / macOS',
    status: 'success',
    timestamp: '1 day ago',
  },
  {
    id: 'l3',
    userId: 'u1',
    ip: '92.45.11.200',
    location: 'London, UK',
    device: 'Safari / iOS',
    status: 'failed',
    timestamp: '3 days ago',
  },
]
